AWSTemplateFormatVersion: '2010-09-09'
Resources:
 S3Bucket:
   Type: AWS::S3::Bucket
   Properties:
     BucketName: krushnat-bucket-demo-github

 IAMRole:
   Type: AWS::IAM::Role
   Properties:
     RoleName: Krushnat-CICD-githubRole
     AssumeRolePolicyDocument:
       Version: '2012-10-17'
       Statement:
         - Effect: Allow
           Principal:
             Service: ec2.amazonaws.com
           Action: sts:AssumeRole
     Policies:
       - PolicyName: MySamplePolicyS3Access
         PolicyDocument:
           Version: '2012-10-17'
           Statement:
             - Effect: Allow
               Action:
                 - s3:*
               Resource: "*"
